"""empty message

Revision ID: a73058479f55
Revises: a6db26154e11
Create Date: 2024-02-06 12:25:37.356361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73058479f55'
down_revision = 'a6db26154e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmPassword')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmPassword', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
